@HostAddress = http://localhost:5133

POST {{HostAddress}}/boardgame
Content-Type: application/json
{
  "name": "Catan",
  "minPlayers": 1,
  "maxPlayers": 4,
  "categories": [
    "Family",
    "Classic"
  ]
}

###
